package org.jfrog.artifactory.client

import org.jfrog.artifactory.client.model.Version
import org.jfrog.artifactory.client.model.impl.VersionImpl
import org.testng.annotations.DataProvider
import org.testng.annotations.Test

/**
 * test version correctness
 *
 * @author Yahav Itzhak (yahavi@jfrog.com)
 */
class VersionTest {

    @Test(dataProvider = "provideVersion")
    public void testVersion(String verStr, String atLeast, boolean expected) {
        Version ver = new VersionImpl()
        ver.version = verStr
        assert ver.isAtLeast(atLeast) == expected
    }

    @DataProvider
    private Object[][] provideVersion() {
        [
//               Version           AtLeast           Expected
                ["1.0.0",          "0.0.0",           true],
                ["1.0.0",          "0.0. ",           true],
                ["1.0.0",          "0.0",             true],
                ["1.0.0",          "0.",              true],
                ["1.0.0",          "0",               true],
                ["1.0.0",          "0.1.0",           true],
                ["1.0.0",          "0.0.1",           true],
                ["1.0.0",          "0.1.1",           true],
                ["1.0.0",          "0.1.",            true],
                ["1.0.0",          "0.1",             true],
                ["1.0.0",          "1.0.0",           true],
                ["1.0.0",          "1.0",             true],
                ["1.0.0",          "1",               true],
                ["1.0.0",          "1.0.1",           false],
                ["1.0.0",          "1.1.0",           false],
                ["1.0.0",          "1.1.",            false],
                ["1.0.0",          "1.1",             false],
                ["1.0.0",          "1.1.1",           false],
                ["1.0.0",          "0.0.0-SNAPSHOT",  true],
                ["1.0.0",          "0.0.1-SNAPSHOT",  true],
                ["1.0.0",          "0.1.0-SNAPSHOT",  true],
                ["1.0.0",          "0.1.1-SNAPSHOT",  true],
                ["1.0.0",          "1.0.0-SNAPSHOT",  false],
                ["1.0.0",          "1.0.1-SNAPSHOT",  false],
                ["1.0.0",          "1.1.0-SNAPSHOT",  false],
                ["1.0.0",          "1.1.1-SNAPSHOT",  false],
                ["1.0.0",          "0-SNAPSHOT",      true],
                ["1.0.0",          "0.0.1-SNAPSHOT",  true],
                ["1.0.0",          "0. .1-SNAPSHOT",  true],
                ["1.0.0",          " .0.1-SNAPSHOT",  true],
                ["1.0.0",          ".0.1-SNAPSHOT",   true],
                ["1.0.0",          "0.1-SNAPSHOT",    true],
                ["1.0.0",          "0.1.1-SNAPSHOT",  true],
                ["1.0.0",          "1-SNAPSHOT",      false],
                ["1.0.0",          "1.0.1-SNAPSHOT",  false],
                ["1.0.0",          "1.1-SNAPSHOT",    false],
                ["1.0.0",          "1.1.1-SNAPSHOT",  false],

//               Version           AtLeast           Expected
                ["1.0.",           "0.0.0",           true],
                ["1.0.",           "0.0. ",           true],
                ["1.0.",           "0.0",             true],
                ["1.0.",           "0.",              true],
                ["1.0.",           "0",               true],
                ["1.0.",           "0.1.0",           true],
                ["1.0.",           "0.0.1",           true],
                ["1.0.",           "0.1.1",           true],
                ["1.0.",           "0.1.",            true],
                ["1.0.",           "0.1",             true],
                ["1.0.",           "1.0.0",           true],
                ["1.0.",           "1.0",             true],
                ["1.0.",           "1",               true],
                ["1.0.",           "1.0.1",           false],
                ["1.0.",           "1.1.0",           false],
                ["1.0.",           "1.1.",            false],
                ["1.0.",           "1.1",             false],
                ["1.0.",           "1.1.1",           false],
                ["1.0.",           "0.0.0-SNAPSHOT",  true],
                ["1.0.",           "0.0.1-SNAPSHOT",  true],
                ["1.0.",           "0.1.0-SNAPSHOT",  true],
                ["1.0.",           "0.1.1-SNAPSHOT",  true],
                ["1.0.",           "1.0.0-SNAPSHOT",  false],
                ["1.0.",           "1.0.1-SNAPSHOT",  false],
                ["1.0.",           "1.1.0-SNAPSHOT",  false],
                ["1.0.",           "1.1.1-SNAPSHOT",  false],
                ["1.0.",           "0-SNAPSHOT",      true],
                ["1.0.",           "0.0.1-SNAPSHOT",  true],
                ["1.0.",           "0. .1-SNAPSHOT",  true],
                ["1.0.",           " .0.1-SNAPSHOT",  true],
                ["1.0.",           ".0.1-SNAPSHOT",   true],
                ["1.0.",           "0.1-SNAPSHOT",    true],
                ["1.0.",           "0.1.1-SNAPSHOT",  true],
                ["1.0.",           "1-SNAPSHOT",      false],
                ["1.0.",           "1.0.1-SNAPSHOT",  false],
                ["1.0.",           "1.1-SNAPSHOT",    false],
                ["1.0.",           "1.1.1-SNAPSHOT",  false],

//               Version           AtLeast           Expected
                ["1.0",            "0.0.0",           true],
                ["1.0",            "0.0. ",           true],
                ["1.0",            "0.0",             true],
                ["1.0",            "0.",              true],
                ["1.0",            "0",               true],
                ["1.0",            "0.1.0",           true],
                ["1.0",            "0.0.1",           true],
                ["1.0",            "0.1.1",           true],
                ["1.0",            "0.1.",            true],
                ["1.0",            "0.1",             true],
                ["1.0",            "1.0.0",           true],
                ["1.0",            "1.0",             true],
                ["1.0",            "1",               true],
                ["1.0",            "1.0.1",           false],
                ["1.0",            "1.1.0",           false],
                ["1.0",            "1.1.",            false],
                ["1.0",            "1.1",             false],
                ["1.0",            "1.1.1",           false],
                ["1.0",            "0.0.0-SNAPSHOT",  true],
                ["1.0",            "0.0.1-SNAPSHOT",  true],
                ["1.0",            "0.1.0-SNAPSHOT",  true],
                ["1.0",            "0.1.1-SNAPSHOT",  true],
                ["1.0",            "1.0.0-SNAPSHOT",  false],
                ["1.0",            "1.0.1-SNAPSHOT",  false],
                ["1.0",            "1.1.0-SNAPSHOT",  false],
                ["1.0",            "1.1.1-SNAPSHOT",  false],
                ["1.0",            "0-SNAPSHOT",      true],
                ["1.0",            "0.0.1-SNAPSHOT",  true],
                ["1.0",            "0. .1-SNAPSHOT",  true],
                ["1.0",            " .0.1-SNAPSHOT",  true],
                ["1.0",            ".0.1-SNAPSHOT",   true],
                ["1.0",            "0.1-SNAPSHOT",    true],
                ["1.0",            "0.1.1-SNAPSHOT",  true],
                ["1.0",            "1-SNAPSHOT",      false],
                ["1.0",            "1.0.1-SNAPSHOT",  false],
                ["1.0",            "1.1-SNAPSHOT",    false],
                ["1.0",            "1.1.1-SNAPSHOT",  false],

//               Version           AtLeast           Expected
                ["1.",             "0.0.0",           true],
                ["1.",             "0.0. ",           true],
                ["1.",             "0.0",             true],
                ["1.",             "0.",              true],
                ["1.",             "0",               true],
                ["1.",             "0.1.0",           true],
                ["1.",             "0.0.1",           true],
                ["1.",             "0.1.1",           true],
                ["1.",             "0.1.",            true],
                ["1.",             "0.1",             true],
                ["1.",             "1.0.0",           true],
                ["1.",             "1.0",             true],
                ["1.",             "1",               true],
                ["1.",             "1.0.1",           false],
                ["1.",             "1.1.0",           false],
                ["1.",             "1.1.",            false],
                ["1.",             "1.1",             false],
                ["1.",             "1.1.1",           false],
                ["1.",             "0.0.0-SNAPSHOT",  true],
                ["1.",             "0.0.1-SNAPSHOT",  true],
                ["1.",             "0.1.0-SNAPSHOT",  true],
                ["1.",             "0.1.1-SNAPSHOT",  true],
                ["1.",             "1.0.0-SNAPSHOT",  false],
                ["1.",             "1.0.1-SNAPSHOT",  false],
                ["1.",             "1.1.0-SNAPSHOT",  false],
                ["1.",             "1.1.1-SNAPSHOT",  false],
                ["1.",             "0-SNAPSHOT",      true],
                ["1.",             "0.0.1-SNAPSHOT",  true],
                ["1.",             "0. .1-SNAPSHOT",  true],
                ["1.",             " .0.1-SNAPSHOT",  true],
                ["1.",             ".0.1-SNAPSHOT",   true],
                ["1.",             "0.1-SNAPSHOT",    true],
                ["1.",             "0.1.1-SNAPSHOT",  true],
                ["1.",             "1-SNAPSHOT",      false],
                ["1.",             "1.0.1-SNAPSHOT",  false],
                ["1.",             "1.1-SNAPSHOT",    false],
                ["1.",             "1.1.1-SNAPSHOT",  false],

//               Version           AtLeast           Expected
                ["1",              "0.0.0",           true],
                ["1",              "0.0. ",           true],
                ["1",              "0.0",             true],
                ["1",              "0.",              true],
                ["1",              "0",               true],
                ["1",              "0.1.0",           true],
                ["1",              "0.0.1",           true],
                ["1",              "0.1.1",           true],
                ["1",              "0.1.",            true],
                ["1",              "0.1",             true],
                ["1",              "1.0.0",           true],
                ["1",              "1.0",             true],
                ["1",              "1",               true],
                ["1",              "1.0.1",           false],
                ["1",              "1.1.0",           false],
                ["1",              "1.1.",            false],
                ["1",              "1.1",             false],
                ["1",              "1.1.1",           false],
                ["1",              "0.0.0-SNAPSHOT",  true],
                ["1",              "0.0.1-SNAPSHOT",  true],
                ["1",              "0.1.0-SNAPSHOT",  true],
                ["1",              "0.1.1-SNAPSHOT",  true],
                ["1",              "1.0.0-SNAPSHOT",  false],
                ["1",              "1.0.1-SNAPSHOT",  false],
                ["1",              "1.1.0-SNAPSHOT",  false],
                ["1",              "1.1.1-SNAPSHOT",  false],
                ["1",              "0-SNAPSHOT",      true],
                ["1",              "0.0.1-SNAPSHOT",  true],
                ["1",              "0. .1-SNAPSHOT",  true],
                ["1",              " .0.1-SNAPSHOT",  true],
                ["1",              ".0.1-SNAPSHOT",   true],
                ["1",              "0.1-SNAPSHOT",    true],
                ["1",              "0.1.1-SNAPSHOT",  true],
                ["1",              "1-SNAPSHOT",      false],
                ["1",              "1.0.1-SNAPSHOT",  false],
                ["1",              "1.1-SNAPSHOT",    false],
                ["1",              "1.1.1-SNAPSHOT",  false],

//               Version           AtLeast           Expected
                ["1.0.0-SNAPSHOT", "0.0.0",           true],
                ["1.0.0-SNAPSHOT", "0.1.0",           true],
                ["1.0.0-SNAPSHOT", "0.0.1",           true],
                ["1.0.0-SNAPSHOT", "0.1.1",           true],
                ["1.0.0-SNAPSHOT", "1.0.0",           true],
                ["1.0.0-SNAPSHOT", "1.0.1",           false],
                ["1.0.0-SNAPSHOT", "1.1.0",           false],
                ["1.0.0-SNAPSHOT", "1.1.1",           false],
                ["1.0.0-SNAPSHOT", "0.0.0-SNAPSHOT",  true],
                ["1.0.0-SNAPSHOT", "0.0.1-SNAPSHOT",  true],
                ["1.0.0-SNAPSHOT", "0.1.0-SNAPSHOT",  true],
                ["1.0.0-SNAPSHOT", "0.1.1-SNAPSHOT",  true],
                ["1.0.0-SNAPSHOT", "1.0.0-SNAPSHOT",  true],
                ["1.0.0-SNAPSHOT", "1.0.1-SNAPSHOT",  false],
                ["1.0.0-SNAPSHOT", "1.1.0-SNAPSHOT",  false],
                ["1.0.0-SNAPSHOT", "1.1.1-SNAPSHOT",  false],

//               Version           AtLeast           Expected
                ["1.0.0-A",        "0.0.0",           true],
                ["1.0.0-A",        "0.1.0",           true],
                ["1.0.0-A",        "0.0.1",           true],
                ["1.0.0-A",        "0.1.1",           true],
                ["1.0.0-A",        "1.0.0",           true],
                ["1.0.0-A",        "1.0.1",           false],
                ["1.0.0-A",        "1.1.0",           false],
                ["1.0.0-A",        "1.1.1",           false],
                ["1.0.0-A",        "0.0.0-B",         true],
                ["1.0.0-A",        "0.0.1-B",         true],
                ["1.0.0-A",        "0.1.0-B",         true],
                ["1.0.0-A",        "0.1.1-B",         true],
                ["1.0.0-A",        "1.0.0-B",         false],
                ["1.0.0-A",        "1.0.1-B",         false],
                ["1.0.0-A",        "1.1.0-B",         false],
                ["1.0.0-A",        "1.1.1-B",         false],

//               Version           AtLeast           Expected
                ["1.0.0-B",        "0.0.0-A",         true],
                ["1.0.0-B",        "0.0.1-A",         true],
                ["1.0.0-B",        "0.1.0-A",         true],
                ["1.0.0-B",        "0.1.1-A",         true],
                ["1.0.0-B",        "1.0.0-A",         true],
                ["1.0.0-B",        "1.0.1-A",         false],
                ["1.0.0-B",        "1.1.0-A",         false],
                ["1.0.0-B",        "1.1.1-A",         false],

//               Version           AtLeast           Expected
                ["12.0.0",         "0.0.0",           true],
                ["12.0.0",         "0.0.2",           true],
                ["12.0.0",         "0.2.0",           true],
                ["12.0.0",         "0.2.3",           true],
                ["12.0.0",         "2.0.0",           true],
                ["12.0.0",         "2.0.3",           true],
                ["12.0.0",         "2.3.0",           true],
                ["12.0.0",         "2.3.4",           true],
                ["12.0.0",         "0.0.12",          true],
                ["12.0.0",         "0.22.0",          true],
                ["12.0.0",         "0.23.34",         true],
                ["12.0.0",         "2.34.45",         true],
                ["12.0.0",         "23.0.0",          false],
                ["12.0.0",         "23.0.34",         false],
                ["12.0.0",         "23.34.0",         false],
                ["12.0.0",         "0.0.0-SNAPSHOT",  true],
                ["12.0.0",         "0.0.2-SNAPSHOT",  true],
                ["12.0.0",         "0.2.0-SNAPSHOT",  true],
                ["12.0.0",         "0.2.3-SNAPSHOT",  true],
                ["12.0.0",         "2.0.0-SNAPSHOT",  true],
                ["12.0.0",         "2.0.3-SNAPSHOT",  true],
                ["12.0.0",         "2.3.0-SNAPSHOT",  true],
                ["12.0.0",         "2.3.4-SNAPSHOT",  true],
                ["12.0.0",         "12.0.0-SNAPSHOT", false]
        ] as Object[][]
    }
}
