updateCommitStatus: &UPDATE_COMMIT_STATUS update_commit_status javaClientSnapshotGit --context "$step_name"

pipelines:
  - name: build_java_client_snapshot
    configuration:
      runtime:
        type: image
        image:
          auto:
            language: java
            versions:
              - "8.0.0"

    steps:
      - name: Snapshot
        type: Bash
        configuration:
          inputResources:
            - name: javaClientSnapshotGit
          integrations:
            - name: ojo
        execution:
          onStart:
            - *UPDATE_COMMIT_STATUS
            - restore_cache_files gradle_cache $res_javaClientSnapshotGit_resourcePath/.gradle
          onExecute:
            - cd $res_javaClientSnapshotGit_resourcePath

            # Set env
            - export CI=true
            - export JFROG_CLI_BUILD_NAME=artifactory-client-java
            - export JFROG_CLI_BUILD_NUMBER=$run_number

            # Download JFrog CLI
            - curl -fL https://getcli.jfrog.io | sh && chmod +x jfrog

            # Configure JFrog CLI
            - ./jfrog rt c ojo --url $int_ojo_rt_url --access-token=$int_ojo_rt_token
            - ./jfrog rt gradlec --use-wrapper --deploy-ivy-desc=false --deploy-maven-desc=true --uses-plugin
              --server-id-resolve ojo --repo-resolve remote-repos
              --server-id-deploy ojo --repo-deploy oss-snapshot-local

            # Run test, build and publish snapshot
            - >
              env -i PATH=$PATH HOME=$HOME GRADLE_OPTS=-Dorg.gradle.daemon=false
              JFROG_CLI_BUILD_NAME=$JFROG_CLI_BUILD_NAME
              JFROG_CLI_BUILD_NUMBER=$JFROG_CLI_BUILD_NUMBER
              ./jfrog rt gradle clean artifactoryPublish -x test
            - ./jfrog rt bp

          onComplete:
            - *UPDATE_COMMIT_STATUS

            # Save gradle cache
            - add_cache_files $res_javaClientSnapshotGit_resourcePath/.gradle gradle_cache